### ISSUE TITLE
InterlockedMin at fixed memory address not translating correctly

### ISSUE THREAD

**Issue by Zorro666** [James-Jones/HLSLCrossCompiler#34]
HLSL Source
[numthreads(1, 1, 1)]
void CSMain (uint id : SV_DispatchThreadID, RWStructuredBuffer<int> distance)
{
	InterlockedMin (distance[2], 6);
}

HLSL ASM
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_uav_structured u0, 4
dcl_thread_group 1, 1, 1
atomic_imin u0, l(2, 0, 0, 0), l(6)
ret 

GLSL output from HLSLCrossCompiler
<snip>
    atomicMin(distance[**0**], 0x6);
<snip>
It should be distance[2]

Full Output

#version 400
#extension GL_ARB_compute_shader : enable
#extension GL_ARB_shader_storage_buffer_object : enable
#extension GL_ARB_shader_atomic_counters : enable
#extension GL_ARB_shader_storage_buffer_object : enable
subroutine void SubroutineType();
struct vec1 {
	float x;
};
struct uvec1 {
	uint x;
};
struct ivec1 {
	int x;
};
buffer Block0 {
	int distance[];
};
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
void main()
{
    //--- Start Early Main ---
    //--- End Early Main ---
    //Instruction 0
    //ATOMIC_IMIN
    atomicMin(distance[0], 0x6);
    //Instruction 1
    //RET
    return;

**Comment by James-Jones** [comment]
Fixed by c76b758ab83733ce50b1f4a44efad5f5dab9a8a0
Unfortunately my commit message lacked the # before the issue number so it has not been linked to this issue correctly.
